name: numpy-dice-hy 
base: core18
version: '1.0' 
summary: Dice roller using numpy. 
description: Dice roller using numpy. 
grade: stable 
confinement: strict 

apps:
  numpy-dice-hy:
    command: bin/numpy_dice_hy.py

parts:
  numpy-dice-hy:
    source: https://github.com/nom666nom/numpy-dice-hy.git 
    plugin: python
    python-version: python3
    source-type: git
    python-packages: [numpy]

